import type { Metadata } from "next";
import { Palanquin_Dark, Pathway_Gothic_One } from "next/font/google";
import "./globals.css";

const pal = Palanquin_Dark({ weight: ["400", "700"], subsets: ["latin"] });
const pathway = Pathway_Gothic_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-pathway",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pal.className} ${pathway.variable} text-white`}>
        {children}
      </body>
    </html>
  );
}
